name: Build Mac installer

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      whlurl:
        description: 'URL for Kolibri whl file'
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Download file
      run: |
        mkdir dist
        wget -O dist/kolibri.whl "${{ github.event.inputs.whlurl }}"
    - name: Run the build
      run: |
        unzip -q "dist/kolibri*.whl" "kolibri/*" -x "kolibri/dist/cext*" -d src/
        rm -rf ./src/kolibri/dist/enum
        pip3 install -r requirements-mac.txt
        export PYTHONPATH=$PYTHONPATH:$PWD/src/kolibri/dist
        mkdir -p logs
        export LIBPYTHON_FOLDER="$(python3 -c 'from distutils.sysconfig import get_config_var; print(get_config_var("LIBDIR"))')"
        ln -s $LIBPYTHON_FOLDER/libpython3.9m.dylib $LIBPYTHON_FOLDER/libpython3.9.dylib
        python3 i18n.py
        python3 kapew.py build
        python3 kapew.py package
    - uses: actions/upload-artifact@v2
      with:
        name: dmg-files
        path: package/osx/kolibri*.dmg
