name: Build Mac installer

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      whlurl:
        description: 'URL for Kolibri whl file'
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run the build
      run: |
        make get-whl whl=${{ github.event.inputs.whlurl }}
        make dependencies
        make build-mac-app
        make build-dmg
    - uses: actions/upload-artifact@v2
      with:
        name: dmg-files
        path: dist/*.dmg
